# Generated by Django 3.2.5 on 2021-07-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='distance',
            field=models.IntegerField(default=0),
        ),
    ]
